/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SdsDemoRouteImport } from './routes/sds-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'

const SdsDemoRoute = SdsDemoRouteImport.update({
  id: '/sds-demo',
  path: '/sds-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sds-demo': typeof SdsDemoRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sds-demo': typeof SdsDemoRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sds-demo': typeof SdsDemoRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sds-demo' | '/settings/preferences'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sds-demo' | '/settings/preferences'
  id: '__root__' | '/' | '/sds-demo' | '/settings/preferences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SdsDemoRoute: typeof SdsDemoRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sds-demo': {
      id: '/sds-demo'
      path: '/sds-demo'
      fullPath: '/sds-demo'
      preLoaderRoute: typeof SdsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SdsDemoRoute: SdsDemoRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
